artifacts_root: artifacts

data ingestion:
  root_dir: artifacts/data_ingestion
  source: data/advertising_data.csv
  data_dir: artifacts/data_ingestion
  STATUS_FILE: artifacts/data_ingestion/status.txt

data validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/advertising_data.csv
  STATUS_FILE: artifacts/data_validation/status.txt  # status of data validation 



# Will make changes
cross_val:
  root_dir: artifacts/cross_val
  data_dir: artifacts/data_ingestion/advertising_data.csv
  final_train_data_path: artifacts/cross_val/data_for_final_train
  final_test_data_path: artifacts/cross_val/data_for_final_train
  best_model_params: artifacts/cross_val/best_model_params
  STATUS_FILE: artifacts/cross_val/status.txt

feature_engineering:
  root_dir: artifacts/feature_engineering
  final_train_data_path: artifacts/cross_val/data_for_final_train
  final_test_data_path: artifacts/cross_val/data_for_final_train
  STATUS_FILE: artifacts/feature_engineering/status.txt


#Changes will need to be done for model_trainer and model_evaluation as we are doing a nested cross validation
model_trainer:
  root_dir: artifacts/model_trainer
  final_train_data_path: artifacts/feature_engineering
  final_test_data_path: artifacts/feature_engineering  
  best_model_params: artifacts/cross_val/best_model_params
  STATUS_FILE: artifacts/model_trainer/status.txt

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/feature_engineering
  model_path: artifacts/model_trainer
  STATUS_FILE: artifacts/model_evaluation/status.txt



  